services:
  - type: worker
    name: congress-follower
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    autoDeploy: false  # Prevents automatic redeploy on GitHub changes
    envVars:
      - key: TRADIER_ACCESS_TOKEN
        value: ""
      - key: TRADIER_ACCOUNT_NUMBER
        value: ""
      - key: TRADIER_USERNAME
        value: "Optional, only for remembering the username"
      - key: LIVE_CONFIG
        value: ""
      - key: TRADIER_IS_PAPER
        value: "True"
      - key: IS_BACKTESTING
        value: "False"
      - key: POLYGON_API_KEY
        value: ""
      - key: DISCORD_WEBHOOK_URL
        value: ""
      - key: DB_CONNECTION_STR
        value: ""
      - key: STRATEGY_NAME
        # This should be the name of the strategy + the live config name
        value: "CongressFollower"
